wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.1
    start_time: 1667934032.789561
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.8.1
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
