wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.4
    start_time: 1668254497.399332
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      - 37
      4: 3.9.4
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
clip_norm:
  desc: null
  value: 0.819431820115507
dropout:
  desc: null
  value: 0.2274176002660815
layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.004020372903708056
method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    goal: minimize
    name: val_loss
minibatch_size:
  desc: null
  value: 1024
name:
  desc: null
  value: Erlend-test-2
parameters:
  desc: null
  value:
    clip_norm:
      distribution: uniform
      max: 1
      min: 1.0e-05
    dropout:
      distribution: uniform
      max: 0.4
      min: 0
    layers:
      values:
      - 2
      - 3
      - 4
      - 5
    lr:
      distribution: uniform
      max: 0.01
      min: 1.0e-05
    minibatch_size:
      values:
      - 512
      - 1024
      - 2048
      - 4096
    recurrent_dropout:
      distribution: uniform
      max: 0.4
      min: 0
    units:
      values:
      - 20
      - 40
      - 60
      - 80
recurrent_dropout:
  desc: null
  value: 0.33975860608965225
units:
  desc: null
  value: 60
